### ISSUE TITLE
No validation for positive numbers in cart

### ISSUE THREAD

**Issue by digidub** [twalton83/Deciem-Regiment-Builder#1]
Currently it's possible to do the following:

- Add 0 of an item to cart - which results in the item being added to the cart but with a quantity of zero. There might be a user use case for this, though I noticed on the site you've copied this from they do not allow this.
- Change cart items to negative numbers (e.g. -12) which causes the total USD to fall into the negatives and also the cart icon in the top right corner to reflect the negative items in the cart.

**Comment by twalton83** [comment]
Both of these issues have been resolved, thank you for pointing it out!
